server:
  port: 8084

spring:
  application:
    name: order-service
  config:
    import:
      - optional:nacos:application-shared.yaml?group=CAMPUS_GROUP&refreshEnabled=true
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:}
        group: CAMPUS_GROUP
      config:
        namespace: ${NACOS_NAMESPACE:}
        group: CAMPUS_GROUP
        file-extension: yaml
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:campus}
    password: ${RABBITMQ_PASSWORD:campus123}
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

knife4j:
  enable: true
  setting:
    language: zh_cn
